### ISSUE TITLE
feat: add HTMX typing, working off of @kitajs/html types.

### ISSUE THREAD

**Issue by jaymanmdev** [hwy-js/hwy#51]
In my personal project, I have types based off off of: https://github.com/kitajs/html/blob/master/htmx.d.ts

My revision: https://github.com/jaymanmdev/pokemon-roundest-with-htmx/blob/dev/src/htmx.d.ts - lines 1-3 are changed to extend Hono's HTML JSX interface.

We could make this a part of Hwy potentially? It probably doesn't fit as part of Hono. Whilst Hono is used widely with HTMX, Hwy is built for HTMX in a way. I am proposing a PR to add my revised d.ts file into Hwy - not sure where it would fit though. :)

**Comment by sjc5** [comment]
Ok let me do a little thinking about how we want to structure the export in the lib, and whether we want to do a new package, or just keep in `hwy` core but make sure to isolate the export. 

In the meantime, @jaymanmdev could you prepare a version of `htmx.d.ts` that adds in comments crediting (1) kita, (2) typed-htmx (what kita copied from), and (3) htmx itself? Make sure it includes their original licenses (MIT, or whatever) and copyright notices / dates / authors.

Then I'll figure out where would be best to export from and create a skeleton and have you fill it in. And over time, if we can convince Kita or typed-htmx to export specific types, then we can replace in this file without having users have to change their installed packages or their `tsconfig.json`.

**Comment by jaymanmdev** [comment]
> Ok let me do a little thinking about how we want to structure the export in the lib, and whether we want to do a new package, or just keep in `hwy` core but make sure to isolate the export.
> 
> In the meantime, @jaymanmdev could you prepare a version of `htmx.d.ts` that adds in comments crediting (1) kita, (2) typed-htmx (what kita copied from), and (3) htmx itself? Make sure it includes their original licenses (MIT, or whatever) and copyright notices / dates / authors.
> 
> Then I'll figure out where would be best to export from and create a skeleton and have you fill it in. And over time, if we can convince Kita or typed-htmx to export specific types, then we can replace in this file without having users have to change their installed packages or their `tsconfig.json`.

Sure thing! Would you like me to inline the Licenses or link them? And should I keep in the original comments by typed-htmx and kita describing the types or strip them out?

**Comment by jaymanmdev** [comment]
> Yep awesome, we're on the same page. Thanks!

Is my approach alright? or would you prefer something like your approach?

**Comment by jaymanmdev** [comment]
> > > Yep awesome, we're on the same page. Thanks!
> > 
> > 
> > Is my approach alright? or would you prefer something like your approach?
> 
> Nope what you're doing there looks great, any version of this that is clear / complete is great :)

Alrighty, cool! I'll get one over to you in a couple minutes.

**Comment by sjc5** [comment]
> > > > Yep awesome, we're on the same page. Thanks!
> > > 
> > > 
> > > Is my approach alright? or would you prefer something like your approach?
> > 
> > 
> > Nope what you're doing there looks great, any version of this that is clear / complete is great :)
> 
> Alrighty, cool! I'll get one over to you in a couple minutes.

No rush at all, I won't decide on where to export from until at earliest tomorrow night, maybe later

**Comment by jaymanmdev** [comment]
No worries, is this complete enough? any revisions that should be made?

```ts
// These types have been adapted from https://github.com/kitajs/html/blob/master/htmx.d.ts - Also based on prior source from typed-htmx and htmx.org

/*
Author: Desdaemon/typed-htmx - (license created by Desdaemon)
Date: July 23rd, 2023
License: ISC (https://github.com/Desdaemon/typed-htmx/blob/main/LICENSE)
*/
/*
Author: kitajs/html (license created and revised by arthurfiorette)
Date: July 21st, 2023 (initially created), July 23rd, 2023 (revised)
License: Apache 2.0 (https://github.com/kitajs/html/blob/master/LICENSE)
*/
/*
Author: big-sky-software/htmx.org (license created by 1cg, revised by carson)
Date: April 14th, 2020 (initially created), April 27th, 2020 (revised)
License: BSD 2-Clause "Simplified" (https://github.com/bigskysoftware/htmx/blob/master/LICENSE)
*/
```

**Comment by sjc5** [comment]
That looks good @jaymanmdev, only thing is I try to keep comment line widths within the prettier default (80 chars)

Ok, I think we can probably do this in `~/packages/core/package.json`:

## Old 

```json
  "main": "dist/index.js",
  "files": [
    "dist"
  ],
```

## New 

```json
  "exports": {
    ".": "./dist/index.js",
    "./types/htmx": "./types/htmx.d.ts"
  },
  "files": [
    "dist",
    "types"
  ],
```

Then just add your file into at `~/packages/core/types/htmx.d.ts`. I'd like to keep it simple and out of the build step, but I think this should work.

If you want to do a PR with those changes against `main`, that would be great.

**Comment by sjc5** [comment]
Let's keep it out of source and just right in the package root for now.

The types inside the src folder are internal types (and exported from the index file to the extent they should be in the main package). Best to treat them totally separate/distinct.

So I'd use the exact names / locations mentioned above

**Comment by sjc5** [comment]
Awesome thanks very much @jaymanmdev, I'll get a beta version of this out tomorrow and if all seems well get that merged in and released. I'm thinking to make it a `0.7.2` because `0.8.0` isn't ready yet, but no reason to postpone this.
