### ISSUE TITLE
add `watchInclusions` like `watchExclusions`

### ISSUE THREAD

**Issue by pillowsoft** [hwy-js/hwy#54]
I'd like to use hwy in a monorepos, but would like hwy to watch and reload changes in other packages in my monorepo. Could you add a `watchInclusions` like `watchExclusions`, but for adding paths to include in watching (and/or would you like a pull request)?

Thanks!

**Comment by sjc5** [comment]
I like this idea @pillowsoft.

I'm mid-way a pretty substantial refactor to the dev tooling side of Hwy, so perhaps not the best time for an outside PR, though I very much appreciate the offer.

I'll give this a bit of a think, but I imagine it should be pretty do-able. Will get back to you in a bit!

**Comment by sjc5** [comment]
Alright, just shipped this as `0.7.2` @pillowsoft: https://github.com/hwy-js/hwy/releases/tag/v0.7.2

Thanks for the great idea!

**Comment by pillowsoft** [comment]
Thank you and thanks for the quick addition!!! It works wonderfully!
