### ISSUE TITLE
Make Cloudflare Pages work

### ISSUE THREAD

**Issue by sjc5** [hwy-js/hwy#6]
I was unaware that Cloudflare supports dynamic imports now: https://twitter.com/jasnell/status/1546498745054814209

There are only a few minor runtime `node:fs` calls in Hwy, and they can pretty easily be converted into JS modules.

It's just a couple JSON files (public file maps), plus a text file (which just serves as a boolean indicator anyway), and css that can easily just be exported instead as a JS string.

So, with a little work, we can get rid of all runtime `node:fs` calls and make Cloudflare Workers / Pages work.

The only thing I'm a bit unfamiliar with is how Wrangler should work for local dev, and how that would work with our current scripts. 

If anyone knows Wrangler well and wants to help with that part, that would be great.

**Comment by sjc5** [comment]
Despite removing runtime `node:fs` calls in #7, this unfortunately turns out not to be sufficient to enable out of the box compat with Cloudflare Workers and Pages. This is for a couple reasons.

1. The Workers runtime does not have `node:url` polyfilled, even in `node_compat` mode. This is likely work-around-able but still annoying.
2. The "happy path" for Workers is to have a single massive bundled output file, which does not pair well with Hwy's build pattern where the output `dist` folder is essentially a mirror of your `src` folder. I have not found a clean way of resolving this without a fairly major departure from current patterns that I am not convinced is wise to implement as default nor "worth it" to implement as a custom Cloudflare-only build step.

If I'm missing something or someone wants to help out with this, that would be excellent. But short of that, I'm going to close this as "won't do" for the time being.

Hopefully this can be revisited again in the future. The way I see it, the burden is somewhat on these edge runtimes to support a reasonably simple, modern, ESM-based Node app. Deno, with all its flaws, is doing pretty good at this, as of course is Bun to a much more liberal degree. I think the ball is in Cloudflare's court to improve their offerings here (not with respect to Hwy of course (:sweat_smile:), just in general). If Hwy is deployable to traditional Node, Lambda serverless, Deno, and Bun, I think that covers pretty good ground despite not being at perfect parity with what Hono itself can be deployed to.

**Comment by sjc5** [comment]
Re-opening this. We're going to make it happen.

**Comment by sjc5** [comment]
Update: Going to limit this to Pages only (not Workers). Looks like Cloudflare is officially recommending that as the path for all new full-stack projects. And it will also make things easier to only need to support one custom Cloudflare approach, not two. Using Workers "Sites" is the way we would need to make Workers work, and there's no point in doing that if Cloudflare themselves are wanting to deprecate it (or at least stop recommending it).

<img width="836" alt="Screenshot 2023-10-13 at 12 30 12 AM" src="https://github.com/hwy-js/hwy/assets/58375830/93588267-98ab-4816-ba5b-973e0cd9efe0">

**Comment by sandys** [comment]
@sjc5 we just discovered hwy a few days back and it was so cool!

we are planning to deploy hwy on our own serverless (using knative). any thoughts on how the Cloudflare workers runtime works ?
The workers nodejs runtime injects some middleware and stuff for load balancing/ip addresses, etc. is there anything else?

im looking to have an equally seamless experience with hwy

**Comment by sjc5** [comment]
Hey there @sandys, I'm so glad that you found Hwy and are liking it!

The Cloudflare Workers runtime (deployed via Cloudflare Pages) is running really smoothly with Hwy now, and it will be ready in the next version.

If you want to try it, you can run `npx create-hwy@0.4.0-beta.16` or check out this repo: https://github.com/sjc5/hwy-cf-pages-test.

We were able to handle all of the Cloudflare Workers specific stuff inside the build step to make it run in the workerd runtime. From a user perspective, it should feel just like developing Hwy for Node.

Your package.json scripts will be a little different if you're using `wrangler pages dev`:

```json
  "scripts": {
    "hwy-prebuild": "tailwindcss -i src/styles/tw-input.css -o src/styles/tw-output.bundle.css",
    "build": "tsc --noEmit && hwy-build",
    "dev:serve": "hwy-dev-serve",
    "dev:wrangler": "wrangler pages dev ./dist --compatibility-flag=\"nodejs_compat\" --port=5555 --live-reload",
    "dev": "npm run build && npm-run-all --parallel dev:*"
  }
```

You'll notice that this uses the `nodejs_compat` compatibility flag, because Hwy still uses some Node APIs under the hood.

In the next release we'll be introducing a Hwy config file (`hwy.config.ts`) so you can specify a deployment target there and the build step will automatically change behavior where needed. That will look something like this:

```ts
import type { HwyConfig } from "@hwy-js/build"

export default {
  dev: {
    port: 5555,
    watchExclusions: ["src/styles/tw-output.bundle.css"],
  },
  deploymentTarget: "cloudflare-pages",
} satisfies HwyConfig;
```

Are you planning to run the workerd runtime on knative? If so, that's something I don't know much about, but it sounds cool! Theoretically the build output at `dist/_worker.js` should run in any workerd environment I would think, as long as the same Node polyfills are included that Cloudflare includes in `nodejs_compat` mode.

**Comment by sandys** [comment]
@sjc5 hey thanks so much for replying!

so ur almost right - we were planning wasmedge (https://wasmedge.org/docs/develop/javascript/hello_world). 
wasmedge comes with out-of-the-box integration with k8s (via DAPR) https://wasmedge.org/book/en/use_cases/frameworks/mesh/dapr

since u already got it working on workerd...how hard is it to port to wasmedge. just curious. Is the difference in runtime pretty substantial ?

**Comment by sjc5** [comment]
Ah that's very interesting @sandys. On a quick scan it looks like our normal Node mode would probably work, given they have Node support. At build time we use a lot of Node APIs, but at runtime it's very minimal (just `node:path` and `node:url` for cross-platform support). It looks like both of those are supported by wasmedge Node polyfills already: https://github.com/WasmEdge/WasmEdge/issues/1535

I'll try to give the wasmedge quickstart a try when I have some time. Meanwhile, would you mind opening a separate issue on this for discussing wasmedge support? Thanks!

**Comment by sandys** [comment]
@sjc5 hey thanks so much for being helpful. the reason i didnt open a new issue was because i was debating between workerd vs wasmedge vs Openfunction functions-framework(https://github.com/OpenFunction/functions-framework-nodejs).

I actually wanted to get your thoughts on which one do you think will have the simplest long term support. I'm happy to use the one that you think is generally simpler for you.
Other than workerd, both wasmedge and functions-framework have pretty decent kubernetes/dapr support.

**Comment by sjc5** [comment]
@sandys On a quick scan it looks like OpenFunction is probably the least compatible, because it seems like they assume you're using Express and CJS. Guessing that workerd / wasmedge are probably more compatible.

**Comment by sandys** [comment]
> @sandys On a quick scan it looks like OpenFunction is probably the least compatible, because it seems like they assume you're using Express and CJS. Guessing that workerd / wasmedge are probably more compatible.

brilliant! thanks for clearing that up.
