### ISSUE TITLE
Form action error on Vercel deployment

### ISSUE THREAD

**Issue by MystPi** [hwy-js/hwy#8]
First off, this framework looks very promising, and I hope to use it in the future! I especially like how it supports deployment to Vercel, my usual host of choice.

To test out the framework I deployed the default app created by the CLI to Vercel. (https://hwy-test.vercel.app) Most of the deployment seems to be working great (and everything works locally), however, the login page's form action results in an error.
![image](https://github.com/hwy-js/hwy/assets/86574651/96a0f9fb-7f4a-46e6-833a-8c54249d0af7)
Logs from the Vercel dashboard:
![image](https://github.com/hwy-js/hwy/assets/86574651/b6762f29-04e6-4d47-aaa4-3b2aae26d4b0)

I chose these options when creating the project: Vercel (serverless), TypeScript, Tailwind CSS, and NProgress

**Comment by MystPi** [comment]
I just read [this](https://github.com/hwy-js/hwy/tree/main/docs) and setting the env var `NODEJS_HELPERS` to `0` did the trick! Maybe it should say something about that in the deployment section of the docs.

**Comment by sjc5** [comment]
Good idea, @MystPi -- we should make it clearer in the docs for sure. I think the docs need an overhaul in general, especially on deployment. This should be in the README when you choose Vercel as a deployment target, but that isn't always very obvious.

Thanks for the issue and the recommendation!
